### PR TITLE
better examples, with details about service accounts

### PR DESCRIPTION
**Pull request by brianberzins**
Documentation request: #41 

- updated documentation regarding service accounts and required permissions
- included examples of setting up pod-reaper with both cluster-wide and namespace-specific permissions
- consolidated examples into an `examples` folder
- expanded examples to include setup of all k8s resources (including service accounts/role bindings/namespaces) to make it easier to understand everything at work
- updated manifest files to be compliant with kubernetes version 1.17

### CODE REVIEW

**Comment by brianberzins** [comment]
Looking for feedback on these examples!

**Comment by brianberzins** [comment]
@JordanSussman or @slushpupie 
how do you feel about these compared to previous examples?

**Comment by slushpupie** [comment]
Seems like reasonable examples to me.

**Comment by brianberzins** [comment]
@slushpupie 
Updated this PR to resolve conflicts

**Pull request merged**
