### PR TITLE
check also for initcontianers in ShouldReap

### PR DESCRIPTION
**Pull request by capetrei**

### CODE REVIEW

**Review by ababiciu — APPROVED** [review]

**Comment by brianberzins** [comment]
Hey @capetrei !
This looks totally legit.

Could you add a changelog entry to this PR and I'll get a new version pushed out!

**Comment by capetrei** [comment]
thank you @brianberzins 
do you want the patch or the minor bumped?

**Comment by brianberzins** [comment]
Minor version bump makes sense to me!

**Comment by capetrei** [comment]
changelog updated to the next minor version (2.13.0)

**Review by brianberzins — APPROVED** [review]

**Pull request merged**
